sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

env:
  - PANDOC_VERSION=1.17.2-1
  - PANDOC_VERSION=1.19.1-1

addons:
  apt:
    packages:
      - luarocks

before_install:
  # install pandoc
  - DOWNLOAD_URL="https://github.com/jgm/pandoc/releases/download"
  - mkdir -p ${HOME}/.local
  - travis_retry curl --location --silent
      ${DOWNLOAD_URL}/${PANDOC_VERSION%-*}/pandoc-${PANDOC_VERSION}-amd64.deb
      -o /tmp/pandoc.deb
  - ar p /tmp/pandoc.deb data.tar.gz | tar xvz --strip-components 2 -C $HOME/.local/

  # Set path to include pandoc executable
  - PATH="${HOME}/.local/bin:$PATH"
  # Set lua path to include luarocks
  - LUA_PATH="$(luarocks path)"
  - export LUA_PATH

install:
  - luarocks make --local rockspecs/panlunatic-scm-0.rockspec

script:
  - git clone https://github.com/tarleb/panlunatic

  # Run tests
  - make test
